# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-25 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0076_auto_20190918_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomer',
            name='catalog_uuids',
            field=models.TextField(blank=True, default=[], help_text='A comma-separated list of catalog UUIDs to transmit.', null=True, verbose_name='Catalog UUIDs'),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='catalog_uuids',
            field=models.TextField(blank=True, default=[], help_text='A comma-separated list of catalog UUIDs to transmit.', null=True, verbose_name='Catalog UUIDs'),
        ),
    ]
